"""Migrating authors, companies and books

Revision ID: 9e3dd7e8b3f7
Revises: 
Create Date: 2025-03-05 00:21:25.778362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3dd7e8b3f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=22), nullable=False),
    sa.Column('last_name', sa.String(length=22), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=22), nullable=False),
    sa.Column('password', sa.String(length=8), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
