"""simple_changes

Revision ID: 139739cf5820
Revises: ba6dec9a437c
Create Date: 2025-03-04 18:04:46.296335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '139739cf5820'
down_revision = 'ba6dec9a437c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('time_stamp')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
