"""Initial migration.

Revision ID: 8bb2437211ee
Revises: ed8727e853d9
Create Date: 2025-03-05 15:47:44.924906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bb2437211ee'
down_revision = 'ed8727e853d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_unit', sa.Integer(), nullable=True))
        batch_op.drop_column('price__unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price__unit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('price_unit')

    # ### end Alembic commands ###
