"""more_changes

Revision ID: fa67165c80bf
Revises: 139739cf5820
Create Date: 2025-03-04 18:11:14.510042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa67165c80bf'
down_revision = '139739cf5820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_stamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('created_stamp')

    # ### end Alembic commands ###
